import Button from '#/components/ui/button'
import type { AnalysisResult } from '#/util/analyse'
import { PiArrowRight } from 'react-icons/pi'
import AgentEvidence from './agent-evidence'
import ConflictingSignals from './conflicting-signals'

type Props = {
  ticker: string
  result: AnalysisResult
  onReset: () => void
}

const RECOMMENDATION_STYLES: Record<
  AnalysisResult['recommendation'],
  { text: string; border: string; label: string }
> = {
  'highly recommended': {
    text: 'text-(--brand-primary)',
    border: 'border-(--brand-primary)',
    label: 'Highly Recommended',
  },
  recommended: {
    text: 'text-(--brand-primary)',
    border: 'border-(--brand-primary)',
    label: 'Recommended',
  },
  neutral: {
    text: 'text-(--text-secondary)',
    border: 'border-(--border-color)',
    label: 'Neutral',
  },
  'caution advised': {
    text: 'text-amber-400',
    border: 'border-amber-400',
    label: 'Caution Advised',
  },
  'not recommended': {
    text: 'text-red-400',
    border: 'border-red-400',
    label: 'Not Recommended',
  },
}

export default function AnalysisReport({ ticker, result, onReset }: Props) {
  const rec = RECOMMENDATION_STYLES[result.recommendation]

  return (
    <div className="w-full max-w-4xl mx-auto px-6 pt-16 pb-28 flex flex-col gap-10">

      {/* Header */}
      <div className="flex items-start justify-between gap-6">
        <div>
          <p className="font-mono text-xs tracking-widest text-(--brand-primary) uppercase mb-2">
            Analysis Report
          </p>
          <h1 className="font-serif font-bold text-[clamp(40px,5vw,64px)] text-(--text-primary) leading-tight">
            {ticker}
          </h1>
        </div>
        <div className="flex flex-col items-end gap-2 pt-2 shrink-0">
          <span
            className={`font-mono text-xs px-3 py-1.5 rounded-full border uppercase tracking-widest bg-(--input-background) ${rec.text} ${rec.border}`}
          >
            {rec.label}
          </span>
          <span className="font-mono text-xs text-(--text-muted) uppercase tracking-widest">
            {result.time_horizon}
          </span>
        </div>
      </div>

      {/* Thesis */}
      <div className="border-t border-(--border-color) pt-8">
        <p className="font-mono text-sm tracking-widest text-(--text-primary) uppercase mb-4">
          Thesis
        </p>
        <p className="text-[clamp(14px,1.6vw,18px)] text-(--text-light) leading-[1.75]">
          {result.thesis}
        </p>
      </div>

      {/* Summary */}
      <div className="border-t border-(--border-color) pt-8">
        <p className="font-mono text-sm tracking-widest text-(--text-primary) uppercase mb-4">
          Summary
        </p>
        <p className="text-base text-(--text-light) leading-relaxed">{result.summary}</p>
      </div>

      {/* Strengths & Risks */}
      <div className="border-t border-(--border-color) pt-8 grid grid-cols-1 md:grid-cols-2 gap-10">
        <div>
          <p className="font-mono text-xs tracking-widest text-(--brand-primary) uppercase mb-5">
            Key Tailwinds
          </p>
          <ul className="flex flex-col gap-3">
            {result.strengths.map((s, i) => (
              <li key={i} className="flex gap-3 text-base text-(--text-light) leading-relaxed">
                <span className="text-(--brand-primary) shrink-0">+</span>
                {s}
              </li>
            ))}
          </ul>
        </div>
        <div>
          <p className="font-mono text-xs tracking-widest text-red-400 uppercase mb-5">
            Key Risks
          </p>
          <ul className="flex flex-col gap-3">
            {result.risks.map((r, i) => (
              <li key={i} className="flex gap-3 text-base text-(--text-light) leading-relaxed">
                <span className="text-red-400 shrink-0">−</span>
                {r}
              </li>
            ))}
          </ul>
        </div>
      </div>

      <AgentEvidence evidence={result.agent_evidence} />

      <ConflictingSignals signals={result.conflicting_signals} />

      {/* Data Gaps */}
      {result.data_gaps.length > 0 && (
        <div className="border-t border-(--border-color) pt-8">
          <p className="font-mono text-sm tracking-widest text-(--text-primary) uppercase mb-4">
            Data Gaps
          </p>
          <ul className="flex flex-col gap-2">
            {result.data_gaps.map((gap, i) => (
              <li key={i} className="text-base text-(--text-muted) leading-relaxed">
                · {gap}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Disclaimer */}
      <div className="border-t border-(--border-color) pt-8">
        <p className="font-mono text-xs text-(--text-muted) leading-relaxed">
          This report is generated by AI agents and is for informational purposes only. Nothing here
          constitutes financial advice. Always consult a licensed financial adviser before making
          investment decisions.
        </p>
      </div>

      {/* Reset */}
      <div className="border-t border-(--border-color) pt-8">
        <Button variant="primary" onClick={onReset} className="flex items-center gap-2">
          Analyse another ticker <PiArrowRight />
        </Button>
      </div>
    </div>
  )
}
